/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['auth.login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['auth.logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['auth.me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['v1.status']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** LoginRequest */
    LoginRequest: {
      identifier: string
      password: string
    }
    /** StatusResource */
    StatusResource: {
      status: string
    }
    /** UserResource */
    UserResource: {
      id: number
      name: string
      nim: string | null
      email: string | null
      role: string
    }
  }
  responses: {
    /** @description Validation error */
    ValidationException: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description Errors overview. */
          message: string
          /** @description A detailed description of each field that failed validation. */
          errors: {
            [key: string]: string[]
          }
        }
      }
    }
    /** @description Unauthenticated */
    AuthenticationException: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description Error overview. */
          message: string
        }
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  'auth.login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['UserResource']
          }
        }
      }
      422: components['responses']['ValidationException']
    }
  }
  'auth.logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @constant */
            message: 'Logged out.'
          }
        }
      }
      401: components['responses']['AuthenticationException']
    }
  }
  'auth.me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['UserResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
    }
  }
  'v1.status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `StatusResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['StatusResource']
          }
        }
      }
    }
  }
}
