/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['auth.login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['auth.logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['auth.me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['v1.status']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all admin accounts */
    get: operations['users.index']
    put?: never
    /** Create a new admin account */
    post: operations['users.store']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/admin/users/{user}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update an admin account */
    put: operations['users.update']
    post?: never
    /** Delete an admin account */
    delete: operations['users.destroy']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** LoginRequest */
    LoginRequest: {
      identifier: string
      password: string
    }
    /** StatusResource */
    StatusResource: {
      status: string
    }
    /** StoreUserRequest */
    StoreUserRequest: {
      name: string
      /** Format: email */
      email: string
      password: string
    }
    /** UpdateUserRequest */
    UpdateUserRequest: {
      name?: string
      /** Format: email */
      email?: string
      password?: string
    }
    /** UserResource */
    UserResource: {
      id: number
      name: string
      nim: string | null
      email: string | null
      role: string
    }
  }
  responses: {
    /** @description Validation error */
    ValidationException: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description Errors overview. */
          message: string
          /** @description A detailed description of each field that failed validation. */
          errors: {
            [key: string]: string[]
          }
        }
      }
    }
    /** @description Unauthenticated */
    AuthenticationException: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description Error overview. */
          message: string
        }
      }
    }
    /** @description Not found */
    ModelNotFoundException: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description Error overview. */
          message: string
        }
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  'auth.login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description `UserResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['UserResource']
          }
        }
      }
      422: components['responses']['ValidationException']
    }
  }
  'auth.logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @constant */
            message: 'Logged out.'
          }
        }
      }
      401: components['responses']['AuthenticationException']
    }
  }
  'auth.me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `UserResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['UserResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
    }
  }
  'v1.status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `StatusResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['StatusResource']
          }
        }
      }
    }
  }
  'users.index': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Array of `UserResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['UserResource'][]
          }
        }
      }
      401: components['responses']['AuthenticationException']
    }
  }
  'users.store': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StoreUserRequest']
      }
    }
    responses: {
      /** @description `UserResource` */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['UserResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      422: components['responses']['ValidationException']
    }
  }
  'users.update': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The user ID */
        user: number
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['UpdateUserRequest']
      }
    }
    responses: {
      /** @description `UserResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['UserResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      404: components['responses']['ModelNotFoundException']
      422: components['responses']['ValidationException']
    }
  }
  'users.destroy': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The user ID */
        user: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['AuthenticationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
}
